sonar.projectKey=cloud-native-app
sonar.projectName=Cloud Native App
sonar.projectVersion=1.0

sonar.sources=frontend,gateway,services
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/vendor/**,**/dist/**,**/build/**,**/__pycache__/**,**/.git/**