name: CI CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  packages: write
  deployment: write

jobs:
  secret-scan:
    name: Secret Scan
    uses: ./.github/workflows/secret-scan.yml
    secrets: inherit

  linting:
    name: Code Linting
    needs: [secret-scanning]
    uses: ./.github/workflows/lint.yml