name: docker-push

on:
  workflow_call:

jobs:
  docker-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile-path: ./frontend/Dockerfile
            context-path: ./frontend
            image-name: cloud-app:v1.0.0

          - dockerfile-path: ./gateway/Dockerfile
            context-path: ./gateway
            image-name: cloud-app-gateway:v1.0.0

          - dockerfile-path: ./services/auth-service/Dockerfile
            context-path: ./services/auth-service
            image-name: cloud-app-auth-service:v1.0.0

          - dockerfile-path: ./services/payment-service/Dockerfile
            context-path: ./services/payment-service
            image-name: cloud-app-payment-service:v1.0.0

          - dockerfile-path: ./services/product-service/Dockerfile
            context-path: ./services/product-service
            image-name: cloud-app-product-service:v1.0.0

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context-path }}
          file: ${{ matrix.dockerfile-path }}
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.image-name }}:${{ github.sha }}